# Generated by Django 4.2.5 on 2023-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('d', 'Dominante'), ('i', 'Influente'), ('s', 'Estabilidade'), ('c', 'Conformado')], max_length=10)),
            ],
        ),
    ]
