# Generated by Django 4.2.5 on 2023-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.IntegerField(choices=[(5, 'Concordo Muito'), (4, 'Concordo'), (3, 'Neutro'), (2, 'Discordo'), (1, 'Discordo Muito')], default=3),
        ),
    ]
